version: '3'
services:
  node-api:
    build: ./node-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./uploads:/app/uploads 

  python-service:
    build: ./python-service
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./uploads:/app/uploads 

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: avishag12
      POSTGRES_DB: document_db  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"   
      - "5672:5672"    

volumes:
  postgres_data: {}
